[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--include=dev"

[[redirects]]
  from = "/*"
  to = "https://misterjk.com/blog"
  status = 301
